
name: Setup Cog
description: Install Cog so you can run, test, and push machine learning models to Replicate.
author: replicate
branding:
  icon: settings
  color: gray-dark

inputs:
  token:
    required: true
    description: "If present, this token is used to authenticate to Replicate using `cog login` so you can push your model."
  cog-version:
    description: "The version of Cog to install"
    required: false
    # This version of Cog adds support for `cog run` on non-GPU environments (like GitHub Actions' default runners)
    default: "v0.8.0-beta3"

runs:
  using: "composite"
  steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2.9.1
  
      - name: Install NVIDIA CUDA Toolkit
        uses: Jimver/cuda-toolkit@6974ecc945579a89135a1e1d9eac96ec361a1171 # v0.2.10

      - name: Setup Cog
        shell: bash
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/download/${{ inputs.cog-version }}/cog_Linux_x86_64
          sudo chmod +x /usr/local/bin/cog
          cog --version

      - name: Log in to Replicate
        shell: bash
        if: ${{ inputs.token != '' }}
        env:
          REPLICATE_API_TOKEN: ${{ inputs.token }}
        run: |
          echo "Found REPLICATE_API_TOKEN in the environment; Authenticating..."
          echo $REPLICATE_API_TOKEN | cog login --token-stdin